<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-NFDA3MBQ" failures="3" tests="3" name="Test(failed)" time="10.98" errors="0" timestamp="2024-07-22T18:23:34 GMT+08:00">
  <testcase classname="testCases.TC3_LoginDataDrivenTest" name="verifyLoginDDT" time="1.461">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC3_LoginDataDrivenTest.verifyLoginDDT(TC3_LoginDataDrivenTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginDDT -->
  <testcase classname="testCases.TC3_LoginDataDrivenTest" name="verifyLoginDDT" time="1.581">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC3_LoginDataDrivenTest.verifyLoginDDT(TC3_LoginDataDrivenTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginDDT -->
  <testcase classname="testCases.TC3_LoginDataDrivenTest" name="verifyLoginDDT" time="1.4">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC3_LoginDataDrivenTest.verifyLoginDDT(TC3_LoginDataDrivenTest.java:73)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginDDT -->
</testsuite> <!-- Test(failed) -->
